This XML file does not appear to have any style information associated with it. The document tree is shown below.
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" xmlns:tools="http://schemas.android.com/tools" android:id="@+id/main" android:layout_width="match_parent" android:layout_height="match_parent" tools:context=".MainActivity">
<TextView android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="Hello World!" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent"/>
<ImageView android:id="@+id/imageView" android:layout_width="wrap_content" android:layout_height="wrap_content" android:scaleType="centerCrop" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent" app:srcCompat="@drawable/bg"/>
<ScrollView android:layout_width="match_parent" android:layout_height="match_parent" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent">
<LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="vertical">
<androidx.constraintlayout.widget.ConstraintLayout android:layout_width="match_parent" android:layout_marginStart="24dp" android:layout_marginEnd="24dp" android:layout_marginTop="60dp" android:background="@drawable/white_full_corner" android:layout_height="match_parent">
<EditText android:id="@+id/editTextText" android:layout_width="0dp" android:layout_height="50dp" android:textColor="@color/black" android:textColorHint="@color/black" android:layout_marginBottom="3dp" android:ems="10" android:inputType="text" android:textSize="16sp" android:hint="City..." android:drawableStart="@drawable/search_icon" android:drawablePadding="8dp" android:padding="8dp" android:background="#00000000" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toStartOf="@+id/button" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent"/>
<androidx.appcompat.widget.AppCompatButton android:id="@+id/button" android:background="@drawable/green_full_corner" android:layout_width="wrap_content" style="@android:style/TextAppearance.Material.Widget.Button" android:layout_height="wrap_content" android:text="Search" android:textColor="@color/white" android:layout_marginEnd="4dp" android:layout_marginBottom="2dp" android:layout_marginTop="2dp" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintTop_toTopOf="parent"/>
</androidx.constraintlayout.widget.ConstraintLayout>
<TextView android:id="@+id/textView" android:layout_width="match_parent" android:layout_height="wrap_content" android:text="25°C" android:textColor="@color/white" android:textSize="70sp" android:textStyle="bold" android:layout_margin="24dp"/>
<androidx.constraintlayout.widget.ConstraintLayout android:layout_width="match_parent" android:layout_margin="24dp" android:layout_height="match_parent">
<ImageView android:id="@+id/imageView2" android:layout_width="170dp" android:layout_height="170dp" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent" app:srcCompat="@drawable/sunny"/>
<LinearLayout android:layout_width="wrap_content" android:layout_height="0dp" android:layout_marginStart="24dp" android:orientation="vertical" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintStart_toEndOf="@+id/imageView2" app:layout_constraintTop_toTopOf="parent">
<LinearLayout android:layout_width="wrap_content" android:layout_height="0dp" android:layout_weight="0.33" android:orientation="vertical" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintStart_toEndOf="@+id/imageView2" app:layout_constraintTop_toTopOf="parent">
<TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:text="Wind Speed" android:textColor="@color/white" android:textSize="13sp"/>
<TextView android:id="@+id/textView3" android:layout_width="match_parent" android:layout_height="wrap_content" android:text="12 km/h" android:textColor="@color/white" android:textSize="18sp" android:textStyle="bold"/>
</LinearLayout>
<LinearLayout android:layout_width="wrap_content" android:layout_height="0dp" android:layout_weight="0.33" android:orientation="vertical" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintStart_toEndOf="@+id/imageView2" app:layout_constraintTop_toTopOf="parent">
<TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:text="Humidty" android:textColor="@color/white" android:textSize="13sp"/>
<TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:text="18%" android:textColor="@color/white" android:textSize="18sp" android:textStyle="bold"/>
</LinearLayout>
<LinearLayout android:layout_width="wrap_content" android:layout_height="0dp" android:layout_weight="0.33" android:orientation="vertical" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintStart_toEndOf="@+id/imageView2" app:layout_constraintTop_toTopOf="parent">
<TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:text="Rain" android:textColor="@color/white" android:textSize="13sp"/>
<TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:text="22%" android:textColor="@color/white" android:textSize="18sp" android:textStyle="bold"/>
</LinearLayout>
<TextView android:id="@+id/textView5" android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="0.33" android:text="Today" android:textColor="@color/white" android:textSize="16sp" android:textStyle="bold" android:layout_marginStart="24dp"/>
<androidx.recyclerview.widget.RecyclerView android:layout_width="match_parent" android:clipToPadding="false" android:paddingStart="16dp" android:paddingEnd="16dp" android:layout_height="0dp" android:layout_weight="0.33"/>
<LinearLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="0.33" android:orientation="horizontal">
<TextView android:id="@+id/textView7" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginStart="24dp" android:layout_marginTop="16dp" android:layout_weight="1" android:text="0ther city" android:textColor="@color/white" android:textSize="16sp" android:textStyle="bold"/>
<TextView android:id="@+id/textView6" android:layout_width="wrap_content" android:layout_height="wrap_content" android:text="View all" android:textSize="16sp" android:layout_marginStart="24dp" android:textColor="@color/white" android:layout_marginTop="16dp"/>
</LinearLayout>
<androidx.recyclerview.widget.RecyclerView android:layout_width="match_parent" android:paddingStart="16dp" android:paddingEnd="16dp" android:clipToPadding="false" android:layout_height="match_parent" android:layout_weight="1"/>
</LinearLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
</LinearLayout>
</ScrollView>
<com.google.android.material.chip.Chip android:layout_width="match_parent" android:layout_height="70dp" android:layout_margin="16dp" android:elevation="3dp" android:padding="4dp" app:cnb_iconSize="20sp" app:cnb_iconColor="@color/black" app:cnb_menuResource="@menu/bottom_menu" app:cnb_orientationMode="horizontal" app:cnb_selectedIconColor="@color/white" app:cnb_radius="50dp" app:cnb_unselectedColor="@color/green" android:id="@+id/chipNavigator" android:background="@drawable/white_full_corner" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent"/>
</androidx.constraintlayout.widget.ConstraintLayout>
